### ISSUE TITLE
README.md里的management拼写错了

### ISSUE THREAD

**Issue by hadongjing** [emqx/emqx-docker#107]
README.md里面加载默认插件的环境变量中的emqx_management写错了，都写成成emqx_mangment了。

**Comment by hadongjing** [comment]
好多哥们直接复制粘帖的，跑不起来容器，还在issues里面转圈呢

**Comment by zhanghongtong** [comment]
Can you share the link, I didn't find "emqx_mangment"

**Comment by hadongjing** [comment]
看起来你已经发现并修正了拼写错误，这个问题可以关闭了。https://github.com/emqx/emqx-docker/commit/3bc64bde9db2a87a6f8475d3f14fcd0e595b8270#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by zhanghongtong** [comment]
THX @hadongjing
