### ISSUE TITLE
the problem of images by "emqx30" branch

### ISSUE THREAD

**Issue by WengangChen** [emqx/emqx-docker#113]
in ``docker.sh`` , use image ``emqx/build-env:alpine3.8-${ARCH}`` to complie the code, but this image can not find in hub.
[the search result](https://hub.docker.com/r/emqx/build-env/tags)

**Comment by WengangChen** [comment]
maybe it should be changed to 3.9?

**Comment by zhanghongtong** [comment]
You can use our develop branch to build the image

**Comment by WengangChen** [comment]
Oh, that means if I won't to use develop version, I need to use tag``v3.0-beta.3`` ? 

the way to build images is changes from ``emqttd`` to ``emqx`` , but the lastest tag ``v3.0-beta.3`` still use the old way to build images, why not release the new one ?

**Comment by zhanghongtong** [comment]
We are now releasing the latest images to the [docker hub](https://hub.docker.com/r/emqx/emqx) so the project does not update the tag. If you need to build the image yourself, it is recommended that you build from the develop branch. If you are just getting the latest image, we recommend using `docker pull emqx/emqx`

**Comment by WengangChen** [comment]
=,= ok, I got it. thank.

In fact, i write a plugin for myself ,so I have to build by myself.

**Comment by zhanghongtong** [comment]
Ok, I am going to close this issue now, if you need it, you can open it at any time.
