### ISSUE TITLE
How can i mount the emqx.conf file

### ISSUE THREAD

**Issue by robertzml** [emqx/emqx-docker#115]
I'm trying to mount my custom config file for emqx.

`docker run -d --name emqx31 -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 --mount type=bind,source=/home/zml/emqx-etc/emqx.conf,target=/opt/emqx/etc/emqx.conf emqx/emqx:v3.1.0 `

but the container told me that
`sed: can't move '/opt/emqx/etc/emqx.confOpgMbG' to '/opt/emqx/etc/emqx.conf': Resource busy`

beside config by environment, is there a way that I can mount my emqx.conf

**Comment by zhanghongtong** [comment]
@robertzml Sorry to reply so late, this is a bug, we will fix it in the latest version.

**Comment by zhanghongtong** [comment]
This bug was fixed in 3.1.2
