### ISSUE TITLE
How to persist data with docker run>?

### ISSUE THREAD

**Issue by hxz393** [emqx/emqx-docker#131]
刚刚试用了emqx最新版,感觉非常强大,但是关于配置持久化的问题一直没有解决.
我翻过先前的Issues,有人提到持久化需要保存四个文件夹/opt/emqx/data /opt/emqx/etc /opt/emqx/lib /opt/emqx/log,经过实地测试并没有用,

just trying like this
下面是我的尝试步骤

first I run the docker container without any mount
首先我直接启动docker镜像:
`docker run -d --name emqx -p 18083:18083 emqx/emqx`

second I copy the dirs from container to local
接着我把容器中的文件拷贝出来:
```
docker cp emqx:/opt/emqx/data ~/emqx/data
docker cp emqx:/opt/emqx/etc ~/emqx/etc
docker cp emqx:/opt/emqx/lib ~/emqx/lib
docker cp emqx:/opt/emqx/log ~/emqx/log
```

third I remove the container and run again with mount volume
然后删除刚启动的容器,加上挂载命令再次启动:
```
docker rm -f emqx
docker run -d --name emqx -p 18083:18083 -v /root/emqx/data:/opt/emqx/data  -v /root/emqx/log:/opt/emqx/log -v /root/emqx/etc:/opt/emqx/etc -v /root/emqx/lib:/opt/emqx/lib emqx/emqx
```

anything is normal,now I access dashboard and login as admin
启动一切正常,访问控制面板用默认账户登录

click Users and create a user 'root', then click Plugins, turn on emqx_auth_http, next click Config button do some changes, like change auth.http.auth_req URL and click confirm button.
点击管理菜单新建一个用户root,再点击插件,启动emqx_auth_http插件,点击插件配置,修改任意请求地址,然后保存

now I delete the container again, run a new container with mount options like before
再次删除启动的容器,和之前一样的命令启动:
```
docker rm -f emqx
docker run -d --name emqx -p 18083:18083 -v /root/emqx/data:/opt/emqx/data  -v /root/emqx/log:/opt/emqx/log -v /root/emqx/etc:/opt/emqx/etc -v /root/emqx/lib:/opt/emqx/lib emqx/emqx
```

access dashboard, can't login with user 'root'. login as admin, checks the Users page, 'root' is not there.
登录控制面板,不能使用新建的root用户登录.使用默认账户登录后查看用户管理页面,root账号不见了.

view the Pulgins page,I can see pugin 'emqx_auth_http' still turn on,but check the config, the changes I made are lost too.
访问插件页面,插件emqx_auth_http状态依然开启,但是配置回到了默认,并没有保存先前的更改.

I have checked the docker container,when I turn on plugin emqx_auth_http, a change is save to 'data/loaded_plugins',like '{emqx_auth_http,true}.'. that's why the plugin status was saved
我进入容器中做观察,当开启插件emqx_auth_http时,会往文件data/loaded_plugins中写入一行内容'{emqx_auth_http,true}.',这是为什么插件状态会保持开启的原因.

but when I change the plugin emqx_auth_http config, nothing to do with file etc/plugins/emqx_auth_http.conf. so I confused, where are my plugin configs save to?
但插件emqx_auth_http配置并不保存在etc/plugins/emqx_auth_http.conf文件中,所以一旦重建容器插件配置恢复了默认.因此我想知道要如何才能保存插件或其他的配置文件?这对于使用k8s平台来说是个必须解决的问题

**Comment by hxz393** [comment]
There is no way to keep your change where you made in dashboard. you can only edit the config files in  etc/*.conf or etc/plugios/*.conf, then mount the files to container.
虽然不能保存在网页端调过的配置,但把修改好配置文件挂载进容器,实测可行,配置能生效.

**Comment by limao0824** [comment]
我按照你的运行，运行不了。你确定你能挂载吗？
/usr/bin/docker-entrypoint.sh: line 122: can't create /opt/emqx/etc/emqx.conf: Permission denied

**Comment by hxz393** [comment]
> 我按照你的运行，运行不了。你确定你能挂载吗？
> /usr/bin/docker-entrypoint.sh: line 122: can't create /opt/emqx/etc/emqx.conf: Permission denied

Just check your login user and permissions, I'm using root all the time.
检查你的登录账户与挂载文件夹权限,我全程使用root用户操作
