### ISSUE TITLE
Building image for arm64v8 

### ISSUE THREAD

**Issue by AaronAutomation** [emqx/emqx-docker#135]
- [X] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------

> BUG REPORT

### Expected behavior
Image build successful

I'm very new so I'm sorry for the possibly silly questions. I'm able to run the  latest emqx container on this machine, but I'd like to add some additional code into the start.sh file to allow the creation of authenticated users. I am unable to successfully run ./docker.sh build. What is the process to do this if I'm on an arm64v8 arch system, or is it even possible? I edited the docker.sh file so that it is;
QEMU_ARCH=aarch64
ARCH=arm64v8
If you can't build an arm64v8 image from an arm64v8 machine, can you build an arm64v8 image on an x86_x64 machine? 

### Actual behavior
Failed

### Test code
root@ip-172-31-17-235://home/ubuntu/emqx-docker/v3.2# ./docker.sh build
+ TARGET=emqx/emqx
+ EMQX_DEPLOY=cloud
+ QEMU_ARCH=aarch64
+ ARCH=arm64v8
+ QEMU_VERSION=v4.0.0
+ EMQX_VERSION=develop
+ BUILD_VERSION=develop
+ main build
+ docker_build
+ echo DOCKER BUILD: Build Docker image.
DOCKER BUILD: Build Docker image.
+ echo DOCKER BUILD: build version -> develop.
DOCKER BUILD: build version -> develop.
+ echo DOCKER BUILD: build from -> .
DOCKER BUILD: build from -> .
+ echo DOCKER BUILD: arch - arm64v8.
DOCKER BUILD: arch - arm64v8.
+ echo DOCKER BUILD: qemu arch - aarch64.
DOCKER BUILD: qemu arch - aarch64.
+ echo DOCKER BUILD: docker repo - emqx/emqx.
DOCKER BUILD: docker repo - emqx/emqx.
+ echo DOCKER BUILD: emqx deploy - cloud.
DOCKER BUILD: emqx deploy - cloud.
+ echo DOCKER BUILD: emqx version - develop.
DOCKER BUILD: emqx version - develop.
+ prepare_qemu
+ echo PREPARE: Qemu
PREPARE: Qemu
+ docker run --rm --privileged multiarch/qemu-user-static:register --reset
standard_init_linux.go:211: exec user process caused "exec format error"

### EMQ version
v3.2

### Docker version

Which docker-engine version?
Docker version 19.03.4, build 9013bf5

How docker info?
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1045-aws
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.523GiB
 Name: ip-172-31-17-235
 ID: UHI7:QUH7:ITUK:JMAR:FCD7:SZAA:LN6G:P7X5:GDFY:SLHE:2XM3:NG2J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

### System

What system do you use?
Ubuntu 18.04

### Hardware
AWS Ubuntu 18.04 server - arm64

**Comment by zhanghongtong** [comment]
Hi, our project is no longer maintained. You can build arm64v8 docker image on x86_64 server by [emqx/emqx-rel](https://github.com/emqx/emqx-rel) project.
```
git clone -b ${version} https://github.com/emqx/emqx-rel
cd emqx-rel
EMQX_DEPS_DEFAULT_VSN=${version} ARCH=arm64v8 QEMU_ARCH=aarch64 make emqx-docker-build
```

**Comment by AaronAutomation** [comment]
Thanks for the reply!
I actually successfully built my image on a x86_64 and was able to run it on my PI with authenticated users as of 5 minutes ago, thanks :D

**Comment by zhanghongtong** [comment]
You are welcome  :)
