### ISSUE TITLE
Unable to restart services in Swarm mode

### ISSUE THREAD

**Issue by dxGuan** [emqx/emqx-docker#136]
Make sure you read and understand http://emqtt.io/docs/v2/index.html.
Use one of the two templates below and delete the rest.

- [√ ] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Expected behavior
EMQX services restart 4 nodes normally

### Actual behavior
EMQX cannot restart services after 2 nodes in the cluster exited abnormally when facing errors:
```
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file,file,{error_status,{error,{file_error,"log/emqx.log.3",enospc}}}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file,file,{error_status,ok}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {file_for_error,filesync,#{file=>"log/error.log",max_no_bytes=>524288000,max_no_files=>5,type=>wrap},{error,{file_error,"log/error.log",enospc}}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,file_for_error,{error_status,{error,{file_error,"log/error.log",enospc}}}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,file_for_error,{error_status,ok}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,file_for_error,{error_status,{error,{file_error,"log/error.log",enospc}}}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,file_for_error,{error_status,ok}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,file_for_error,{error_status,{error,{file_error,"log/error.log",enospc}}}}
emqx_emqx.0.jda3ci6glw7u@mango-vm002    | Logger - error: {disk_log,file_for_error,['2019-11-18T04:14:23Z']:emqx exit abnormally
```

### EMQ version
v3.2.4

### Docker version

```bash
Docker version 19.03.4, build 9013bf583a
```

How docker info?

```bash
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 8
  Paused: 0
  Stopped: 6
 Images: 97
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 1mkaoh1v68hr1b685s4i6y7rj
  Is Manager: true
  ClusterID: 3u6eg2pt7hq4oh6xy28cpgsun
  Managers: 1
  Nodes: 4
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.21.255.177
  Manager Addresses:
   172.21.255.177:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-52-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.527GiB
 Name: mango-vm001
 ID: CTLR:ZLZO:K5KS:VYNX:TFY5:QI3Q:XDTN:CK5V:SC3J:IPEW:KLK2:3QKY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### System

Ubuntu 18.04 LTS

### Hardware
4c 8G

**Comment by zhanghongtong** [comment]
@dxGuan Hi, we have not tried the docker swarm cluster, we recommend you use k8s

**Comment by dxGuan** [comment]
> @dxGuan Hi, we have not tried the docker swarm cluster, we recommend you use k8s

I do really love to transfer to k8s while it takes time cause this matters the whole deployment procedure and basic architecture of our system. 

So I want to know if is there any way that I can recover my emqx-cluster or I have to take down the swarm services and re-deploy it?

Really hope you fellows can do some tests on the swarm cluster and I believe there are quite amount of users who deploy with swarm, though it's not as much as k8s.

Thx.

**Comment by zhanghongtong** [comment]
According to your log, we suspect that the server is running out of disk space, please check your disk space.

**Comment by dxGuan** [comment]
Yeah, the two of the nodes exited with this error and I had free some spaces on the host machine accordingly, but they still cannot restart after this.

**Comment by zhanghongtong** [comment]
Please provide more information

**Comment by dxGuan** [comment]
Cool, but what kinda information are you asking for?
If you are referring error logs, the logs showed lack of space are all I can get from EMQX's error.log which are also the logs from docker.

If you are demanding others, please feel free to tell me about it.

**Comment by zhanghongtong** [comment]
Can you show us the contents of `log/emqx.log.*` and ` log/erlang.log.*` ?

**Comment by dxGuan** [comment]
My bad, in order to recover the environment, I reclaim all the volumes from docker in the error nodes and I am not able to show you the contents of these logs.

Luckily, the cluster can scale up this two nodes and everything seems fine now in prod env.

I will try to re-produce the error case in test env and show you the logs you've mentioned above asap.

Closing this issue by now and I'll re-open it if it occurs again, thx for your help @zhanghongtong .

**Comment by zhanghongtong** [comment]
You are welcome :)
