### ISSUE TITLE
ENV 3.0

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-docker#69]
Hi All, 
what are the docker ENV vars that will work with beta3.0?
I tried:
-e EMQX_ADMIN_PASSWORD=xxxx
and that worked. 
But i am not sure other env are working like:
-e EMQX_MQTT__ALLOW_ANONYMOUS=false
On the 2.9 it was working with:
-e EMQ_MQTT__ALLOW_ANONYMOUS=false

**Comment by zmstone** [comment]
fixed here: https://github.com/emqx/emqx-docker/commit/8194f38f2ae49d5e51ddeeed7f8f08d57fdde2cd
@rjbaat please give it a try.

**Comment by rjbaat** [comment]
Oke thnx! Does this also mean all the normal ENV vars that where usable on the previous emq versions  (2.3.11) should be working again?

**Comment by spring2maz** [comment]
@rjbaat yes.
