### ISSUE TITLE
can't sub some $SYS topic

### ISSUE THREAD

**Issue by wuxingzhong** [emqx/emqx-docker#76]
- [x] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Expected behavior
1.  use docker image to  run emq,  I can't sub  `$SYS/brokers/${node}/clients/`  topic. 
1.  some result run in  k8s
1.  I  use rpm package to install and run emq, I can sub `$SYS/brokers/${node}/clients/`  topic
1. The acl permission issue has been excluded

### Actual behavior
use docker to run 
![image](https://user-images.githubusercontent.com/7947984/46216235-b3333b00-c371-11e8-8f3a-6bbc1d37945d.png)
use rpm package install
![image](https://user-images.githubusercontent.com/7947984/46216332-e970ba80-c371-11e8-9a0d-ff090476c8d0.png)

### Test code

in two  terminal., run bash

```bash
 mosquitto_sub -h 127.0.0.1  -p 1883 -t \$SYS/brokers/#
```
### EMQ version
2.3.4  2.3.11 
### Docker version
Docker version 18.06.1-ce, build e68fc7a

### System
CentOS Linux release 7.5.1804 (Core)

**Comment by Gilbert-Wong** [comment]
Thanks for your issue, @zhanghongtong would check it.

**Comment by Gilbert-Wong** [comment]
It would be better if you open issue with English :p

**Comment by wuxingzhong** [comment]
use docker to run 
![image](https://user-images.githubusercontent.com/7947984/46239613-3b92f980-c3cd-11e8-94b7-e1d754aa44f8.png)

**Comment by zhanghongtong** [comment]
The default ACL rule only allows the address of `127.0.0.1` to subscribe to the topic of `$SYS/#`. You can refer to [this document](http://emqtt.io/docs/v2/config.html#allow-anonymous-and-acl-file) to modify etc/acl.conf.

**Comment by wuxingzhong** [comment]
I fogeted  to enable  emq_modules
