### ISSUE TITLE
Add Apache 2.0 License

### ISSUE THREAD

**Issue by tpiecora** [emqx/emqx-docker#78]
- [x] FEATURE REQUEST

### Missing feature
Apache 2.0 License

### Justification
Please add the Apache 2.0 to this repository so that it is consistent with the emqx license and can be used without concern over it's licensing.

### Workarounds
none

**Comment by Gilbert-Wong** [comment]
Hi, @tpiecora , the LICENSE has been added to emqx30 branch, please check it.
