### ISSUE TITLE
Not Clear What is Current Production-Ready Version

### ISSUE THREAD

**Issue by rv-ladams** [emqx/emqx-docker#83]
Make sure you read and understand http://emqtt.io/docs/v2/index.html.
Use one of the two templates below and delete the rest.

- [ ] BUG REPORT
- [x] FEATURE REQUEST

-------------------------------------------------------------------------------
> FEATURE REQUEST

### Missing feature

Documentation

### Justification
Tell us why you would like to see this feature added.

It would be useful to know which branch in the Repo is considered production-ready.  Right now there are multiple branches related to different versions.

Also because the master branch is without a license it makes it unclear if we should be using that one.  So I'm requesting that we add the Apache license to the master branch if that is indeed the production ready branch.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

**Comment by Gilbert-Wong** [comment]
Sorry for unclear documentation, you can refer this [link](http://emqtt.io/docs/v3/index.html), you need to use git to checkout emqx30 branch, use the dockfile in emqx30 branch.

**Comment by zhanghongtong** [comment]
We recently uploaded the docker image to the Docker hub. You can use the `image:tag` to determine which version to use. We will continue to maintain the [Docker hub repository](https://hub.docker.com/r/emqx/emqx/).

**Comment by rv-ladams** [comment]
Thank you for your help and quick responses.  Closing this issue now.
