### ISSUE TITLE
ACL rules through env variables

### ISSUE THREAD

**Issue by optionsome** [emqx/emqx-docker#86]
- [ x] FEATURE REQUEST

-------------------------------------------------------------------------------
> FEATURE REQUEST

### Missing feature
It does not seem to be possible to define ACL rules through env variables passed to the docker container.
### Justification
It would be convenient if you could define ACL rules through env variable(s).

**Comment by zhanghongtong** [comment]
Sorry, we have no plans to add this feature for now. You can use `-v` to bind your ACL rules in `docker run`.
