### ISSUE TITLE
Docker version tags

### ISSUE THREAD

**Issue by optionsome** [emqx/emqx-docker#88]
- [ x] FEATURE REQUEST

-------------------------------------------------------------------------------
> FEATURE REQUEST

### Missing feature
When you release new versions of the latest image, could you also upload a version tagged image.

### Justification
Having version locked images creates trust in the software. You can have implementations that use emqx and not worry too much that something gets changed which breaks the emqx docker container in your environment or breaks an implementation of emqx built on top of the emqx docker image.

**Comment by zhanghongtong** [comment]
Each version after `v3.0-rc.1 ` will publish the corresponding image and tag on the [docker hub](https://hub.docker.com/r/emqx/emqx/tags/).

**Comment by optionsome** [comment]
I assume that latest tag will eventually also be based on the version 3.x? Will you leave version 2.x to docker hub under some tag?

**Comment by zhanghongtong** [comment]
We have no plans to upload historical versions to docker hub for the time being.
